---
id: Timezone
name: Timezone
full: Timezone library
description: >-
  A library for parsing timezone databases and generating VTIMEZONE iCalendar
  components.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Timezone
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 2.0.0alpha4
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/date: ^3
      horde/icalendar: ^3
      horde/vfs: ^3
  optional:
    composer:
      horde/test: ^3
  dev:
    composer:
      horde/test: ^3
