---
id: Timezone
name: Timezone
full: Timezone library
description: >
  Library for parsing timezone databases and generating VTIMEZONE iCalendar
  components.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Timezone
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 1.1.1
  api: 1.1.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Date: ^2.3
      pear.horde.org/Horde_Icalendar: ^2
      pear.horde.org/Horde_Vfs: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
